name: build

on:
  pull_request:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  publish:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@v1
    with:
      upload_to_pypi: ${{ (github.event_name == 'release') && (github.event.action == 'released') }}
      test_command: python -c "from asdf import open, AsdfFile, info, config_context, get_config, ValidationError, IntegerType, Stream, ExternalArrayReference"
    secrets:
      pypi_token: ${{ secrets.PYPI_PASSWORD_ASDF_MAINTAINER }}
